#!/usr/bin/env bash
#Ubuntu-20.04
#Install curl
apt-get update
apt-get install curl -y
#Install kubectl
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
chmod +x ./kubectl 
sudo mv ./kubectl /usr/local/bin/kubectl
#Install VirtualBox
apt-get update 
apt-get install virtualbox -y
#Requires manual submitted
#apt-get install virtualbox-ext-pack -y 
#Install Minikube
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
mkdir -p /usr/local/bin/
install minikube /usr/local/bin/
